# Server settings
server:
  port: 8080
  address: 127.0.0.1
spring:
  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  # DATASOURCE
  datasource:
    # orcle数据库
    # driverClass: oracle.jdbc.OracleDriver
    # url: jdbc:oracle:thin:@127.0.0.1:1521:ZERO
    # username: ideas
    # password: 123456

    # mysql数据库
    # driverClass: com.mysql.jdbc.Driver
    # url: jdbc:mysql://127.0.0.1:3306/idea?useUnicode=true&characterEncoding=utf-8
    # username: root
    # password: 123456

    # mycat主从备份/读写分离
    driverClass: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.171.135:8066/TESTDB?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/idea?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.idea.bms.model  # 注意：对应实体类的路径