server:
  port: 8080
  address: 127.0.0.1
spring:
  application:
    name: bms-service
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  datasource:
    driverClass: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.26.128:3306/idea?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:1111/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.idea.bms.model  # 注意：对应实体类的路径
token:
  validTime: 3600